//non-essential
// works as intended
//get all customers data
GET http://localhost:3000/customers/ HTTP/1.1

###

//essential
//works as intended
//get data from specific customer, here customer id 1
GET http://localhost:3000/customers/1 HTTP/1.1

###

//non-essential
//does not work yet
//add a new customer, here customer id:10
PUT http://localhost:3000/customers/10 HTTP/1.1

###

//non-essential
// returns all customers
//delete customer id:10
DELETE http://localhost:3000/customers/10 HTTP/1.1

###

//non-essential
// returns HTML error
//add name, email, password to all customers
POST http://localhost:3000/customers/1 HTTP/1.1