//essential
//get all products
//works
GET http://localhost:3000/products/ HTTP/1.1

###

//essential
//get summarized product info of all products
//works
GET http://localhost:3000/products/info HTTP/1.1

###

//essential
//get product info for product id:1
//works
GET http://localhost:3000/products/1 HTTP/1.1

###
//get all types of animals
//returns nothing
GET http://localhost:4000/animals HTTP/1.1

###

//essential
//get summarized info for all categories
//returns nothing
GET http://localhost:4000/categories HTTP/1.1

###

//essential
//get summarized info for all subcategories
//returns nothing
GET http://localhost:4000/subcategories HTTP/1.1

###

//essential
//get items from category:Food
//returns nothing
GET http://localhost:3000/products/Food HTTP/1.1